Changing AVM codec description
AOMediaCodec/libavif pull request #1726
Opened 2023-11-05 15:12 UTC by Jamaika1

2023-11-06 09:38 UTC, y-guyon requested changes
Thank you for your contribution.

These changes should also be made in `avifdec`.

2023-11-06 09:38 UTC, y-guyon commented on apps/avifenc.c
> +    printf("    -c,--codec C                      : AV1/AV2 codec to use (choose from versions list below)\n");
`AVIF_CODEC_AVM` is an experimental feature, so I would avoid mentioning AV2 if `AVIF_CODEC_AVM` is OFF.

Suggestion:
```c
printf(" -c,--codec C       : codec to use (choose from versions list below)\n");
```

2023-11-06 09:38 UTC, y-guyon commented on apps/avifenc.c
> +        fprintf(stderr, "ERROR: Cell size %u is bigger %s than the maximum AV1/AV2 frame size 65536.\n", *cellSize, dimensionStr);
Suggestion:

```c
fprintf(stderr, "ERROR: Cell size %u is bigger %s than the maximum codec frame size 65536.\n", *cellSize, dimensionStr);
```

2023-11-06 09:38 UTC, y-guyon commented on apps/avifenc.c
>             settings->jobs);
Suggestion:

```c
    printf("Encoding with codec '%s' speed [%s], color quality [%d (%s)], alpha quality [%d (%s)]%s, %s, %d worker thread(s), please wait...\n",
           codecName ? codecName : "none",
           speedStr,
           encoder->quality,
           qualityString(encoder->quality),
           encoder->qualityAlpha,
           qualityString(encoder->qualityAlpha),
           gainMapStr,
           encoder->autoTiling ? "automatic tiling" : manualTilingStr,
           settings->jobs);
```

2023-11-06 09:38 UTC, y-guyon commented on apps/avifenc.c
> +                    fprintf(stderr, "ERROR: AV1/AV2 Codec cannot encode: %s\n", arg);
Suggestion:

```c
fprintf(stderr, "ERROR: Codec %s is unrecognized, unavailable or can only decode\n", arg);
```

2023-11-06 09:38 UTC, y-guyon commented on apps/avifenc.c
>      }
Suggestion:

```c
    printf(" * Coded color total size: %" AVIF_FMT_ZU " bytes\n", byteSizes.colorSizeBytes);
    printf(" * Coded alpha total size: %" AVIF_FMT_ZU " bytes\n", byteSizes.alphaSizeBytes);
    if (byteSizes.gainMapSizeBytes > 0) {
        printf(" * Coded gain map total size: %" AVIF_FMT_ZU " bytes\n", byteSizes.gainMapSizeBytes);
    }
```

2023-12-14 14:59 UTC, vrabaud commented
Hi, can you please rebase and take the comments into account. Thx

2024-01-11 09:37 UTC, y-guyon approved these changes

2024-01-11 09:38 UTC, y-guyon commented
Thank you for rebasing. There was no notification so we forgot to check this pull request afterwards.

I rebased it myself again.

2024-01-11 09:39 UTC, merged