Build SVT with clang on Windows.
AOMediaCodec/libavif pull request #2194
Opened 2024-06-05 13:23 UTC by vrabaud

The CI started failing like in
https://github.com/AOMediaCodec/libavif/issues/2033

2024-06-05 13:32 UTC, y-guyon approved these changes

2024-06-05 14:01 UTC, vrabaud commented
Hmmm, this is erratic. It failed on my own actions but not here. https://github.com/vrabaud/libavif/actions/runs/9384941793/job/25841880554
It fails when encoding with SVT and decoding with gav1.
GitHub images are probably being updated, let's wait.

2024-06-05 14:22 UTC, wantehchang requested changes

2024-06-05 14:22 UTC, wantehchang commented on .github/workflows/ci-windows.yml
> +      # https://github.com/AOMediaCodec/libavif/issues/2033#issuecomment-1960062751.
The SEH exception code is different: 0xc0000005 vs. 0xc000001d in https://github.com/AOMediaCodec/libavif/issues/2033. So we should not assume this is the same Visual Studio 2022 bug.

I haven't found a webpage that tabulates the SEH exception codes, but my web searches shows that 0xc0000005 is access violation and 0xc000001d is illegal instruction.

2024-06-05 15:06 UTC, vrabaud commented
Let's wait for the deployment of windows latest 20240603 to be done, it will have VS code 17.10 everywhere. We'll clear the caches and see if it still happens.

2024-06-07 10:51 UTC, vrabaud commented
The windows-latest is fully deployed. I repurposed that PR by upgrading another library to see if the CI still fails.

2024-06-07 14:04 UTC, wantehchang commented
Vincent: We still got the "SEH exception with code 0xc0000005 thrown in the test body." error in windows-latest.

On the other hand, two pull requests of Vignesh's passed yesterday:
https://github.com/AOMediaCodec/libavif/pull/2191
https://github.com/AOMediaCodec/libavif/pull/2195

2024-06-07 15:24 UTC, vrabaud commented
Right, the windows CI was not run, only the windows-installed, and it does not include SVT.

2024-06-11 12:41 UTC, wantehchang commented
Vincent: I did some experiments in my pull request https://github.com/AOMediaCodec/libavif/pull/2199 last night. I did not track this down, but I have two findings.

1. The tests fail whenever libgav1 is used as the decoder:

```
[  FAILED  ] All/CodecTest.EncodeDecode/2, where GetParam() = (1, 3)
[  FAILED  ] All/CodecTest.EncodeDecode/5, where GetParam() = (4, 3)
[  FAILED  ] All/CodecTest.EncodeDecode/8, where GetParam() = (5, 3)
```

The value of `AVIF_CODEC_CHOICE_LIBGAV1` is 3. You can also verify this by inspecting avifcodectest.cc.

2. The "Build aom" step failed, yet the "Build libavif (ninja)" step still succeeded. See

https://github.com/AOMediaCodec/libavif/actions/runs/9415816061/job/25937592690?pr=2194

This does not make sense, because the linking of the executable programs should fail (aom.lib is missing). This may indicate we are still using a cache file. Could you look into this? Thanks.

2024-06-11 13:03 UTC, wantehchang commented
Vincent: In https://github.com/AOMediaCodec/libavif/actions/runs/9415816061/job/25937592690?pr=2194 I see the caches for ext and build/_deps are NOT used. Only the cache for ~/.cargo is used. So I can't explain why "Build aom" failed yet "Build libavif (ninja)" still succeeded.

I will try to reproduce the test failure on my Windows laptop later today.

2024-06-11 13:13 UTC, wantehchang commented
Vincent: Thank you for your reply. I see the following in https://github.com/AOMediaCodec/libavif/actions/runs/9415816061/job/25937592690?pr=2194:

```
-- libavif(AVIF_CODEC_AOM=LOCAL): compiled library not found at D:/a/libavif/libavif/ext/aom/build.libavif/aom.lib, using FetchContent
-- libavif(AVIF_CODEC_AOM=LOCAL): ext/aom found; using as FetchContent SOURCE_DIR
-- libavif(AVIF_CODEC_AOM=LOCAL): configuring aom
```

We probably should not use an existing ext/aom as the libaom source dir.

2024-06-11 21:00 UTC, wantehchang commented
Vincent: I finally found a bug that matches what we are seeing in avifcodectest in the windows-latest image: https://github.com/actions/runner-images/issues/10004

I am testing a workaround now.

2024-06-12 16:17 UTC, wantehchang approved these changes

2024-06-12 19:55 UTC, merged