Set codec-specific options for color or alpha only
AOMediaCodec/libavif pull request #534
Opened 2021-03-06 01:59 UTC by wantehchang

Add a new syntax for codec-specific options so that they can be applied
to the color or alpha sub-image only.

1. <key>=<value> applies to both color and alpha (if present).
2. color:<key>=<value> applies only to color.
3. alpha:<key>=<value> applies only to alpha (if present).

Fix https://github.com/AOMediaCodec/libavif/issues/533.

2021-03-06 02:18 UTC, wantehchang commented
Joe: Please don't review this pull request. I found a problem during testing.

2021-03-06 07:28 UTC, tongyuantongyu requested changes
Regarding film grain, I'm not very sure if it can be applied to alpha images (or generally monochrome images) or not, and I can't find a word about it in spec. aom encodes it just fine but refuses to decode it, while dav1d and libgav1 decode it to some junk image. (but looks the same)

2021-03-09 01:20 UTC, wantehchang commented on apps/avifenc.c
> +        printf("    2. color:<key>=<value> applies only to the color sub-image.\n");
Done.

2021-03-09 01:25 UTC, wantehchang commented
Joe, Yuan Tong: This PR is ready for review now. Thanks!

The codec-specific options section of the avifenc help message now looks like this:

```
aom-specific advanced options:
    1. <key>=<value> applies to both the color sub-image and the alpha sub-image (if present).
    2. color:<key>=<value> or c:<key>=<value> applies only to the color sub-image.
    3. alpha:<key>=<value> or a:<key>=<value> applies only to the alpha sub-image (if present).
       Since the alpha sub-image is a monochrome image, the options that refer to the chrome planes, such as
       enable-chroma-deltaq=B, should not be used with the alpha sub-image. In addition, the film grain options
       are unlikely to make sense for the alpha sub-image.

    aq-mode=M                         : Adaptive quantization mode (0: off (default), 1: variance, 2: complexity, 3: cyclic refresh)
    cq-level=Q                        : Constant/Constrained Quality level (0-63, end-usage must be set to cq or q)
    enable-chroma-deltaq=B            : Enable delta quantization in chroma planes (0: disable (default), 1: enable)
    end-usage=MODE                    : Rate control mode (vbr, cbr, cq, or q)
    sharpness=S                       : Loop filter sharpness (0-7, default: 0)
    tune=METRIC                       : Tune the encoder for distortion metric (psnr or ssim, default: psnr)
    film-grain-test=TEST              : Film grain test vectors (0: none (default), 1: test-1  2: test-2, ... 16: test-16)
    film-grain-table=FILENAME         : Path to file containing film grain parameters
```

2021-03-09 01:44 UTC, joedrago commented
The changes look good to me. Does this change impose any kind of minimum requirement on libaom to work?

2021-03-09 01:50 UTC, wantehchang commented
Joe: Thanks for the review! This change does not impose any kind of minimum requirement on libaom. The color: and alpha: prefixes are processed entirely in src/codec_aom.c and are transparent to libaom.

2021-03-09 01:54 UTC, merged